# Generated by Django 5.2 on 2025-05-06 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CyberAttackType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cyber_attack_type', models.CharField(choices=[('DDOS', 'DDoS'), ('MALWARE', 'Malware'), ('PHISHING', 'Phishing'), ('BRUTE_FORCE', 'Brute Force')], max_length=20)),
                ('source_country', models.CharField(max_length=100)),
                ('target_country', models.CharField(max_length=100)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('attack_timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
